apiVersion: skaffold/v1
kind: Config
metadata:
  name: spring-boot-microservice
build:
  artifacts:
  - image: sivakumarsagar/micro-service
# deploy:
#   kubectl:
#     manifests:
#     - hello-kubernetes.yaml
deploy:
  helm:
    releases:
    - name: micro-service-devops
      chartPath: micro-service
      values:
        image: sivakumarsagar/micro-service
